name: vehicle_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.2
  flutter_slidable: ^3.1.2
  flutter_speed_dial: ^7.0.0
  http: ^1.4.0
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
